import { performance } from "node:perf_hooks";

import { analyzeM0 } from "../../application/src/analyze-m0.js";
import { analyzeProfile, type AnalyzeProfileCommand } from "../../application/src/analyze-profile.js";
import { importCatalog } from "../../catalog/src/import-catalog.js";
import { openCatalogSnapshot, type CatalogSnapshot } from "../../catalog/src/open-catalog-snapshot.js";
import { validateRelationshipResponse } from "../../contracts/src/relationship-response-contract.js";
import { VersionedResultCache } from "../../engine-core/src/index.js";
import { analyzeM5 } from "../../relationship-engine/src/m5.js";
import { analyzeM4 } from "../../relationship-engine/src/m4.js";
import { unavailableM3Projection } from "../../relationship-engine/src/m3.js";
import type { RealityGateAssessment } from "../../relationship-engine/src/reality-gates.js";
import type { DevelopmentTestDefinition } from "./read-development-test-matrix.js";
import type { MatrixAssertionExecution } from "./report-language-runner.js";

export async function executePerformanceStabilityMatrix(input: { readonly definitions: readonly DevelopmentTestDefinition[]; readonly catalog: CatalogSnapshot; readonly snapshotPath: string; readonly repositoryRoot: string }): Promise<readonly MatrixAssertionExecution[]> {
  const records: MatrixAssertionExecution[] = [];
  for (const definition of input.definitions.filter((item) => item.suite === "08_性能稳定性")) records.push(await execute(definition.testId, input));
  return Object.freeze(records);
}

async function execute(testId: string, input: { catalog: CatalogSnapshot; snapshotPath: string; repositoryRoot: string }): Promise<MatrixAssertionExecution> {
  const startedAt = performance.now();
  try {
    let details: Record<string, unknown> = {};
    switch (testId) {
      case "PF-001": { const values = Array.from({ length: 10 }, () => stable(success(analyzeProfile(command(), input.catalog)))); check(values.every((value) => value === values[0]), "repeated business output changed"); details = { runs: 10 }; break; }
      case "PF-002": { const before = performance.now(); const values = await Promise.all(Array.from({ length: 100 }, async (_, index) => success(analyzeProfile(command({ subject: subject(`C-${index}`) }), input.catalog)))); check(new Set(values.map((value) => value.requestId)).size === 100, "request IDs crossed"); check(values.every((value, index) => value.m0.fields.input_validation && value.relationship.m5.fit.isSuccessProbability === false && value.requestId !== values[(index + 1) % values.length]?.requestId), "concurrent state crossed"); const duration = performance.now() - before; check(duration <= 10_000, `100 requests took ${duration}ms`); details = { requests: 100, durationMs: duration }; break; }
      case "PF-003": { const cache = new VersionedResultCache<string>(); cache.set(input.catalog.manifest.rulesetDigest, "request", "old"); check(cache.get(`${input.catalog.manifest.rulesetDigest}-next`, "request") === undefined, "old cache survived ruleset change"); details = { versionScoped: true }; break; }
      case "PF-004": { const before = performance.now(); const opened = openCatalogSnapshot(input.snapshotPath); const count = opened.diagnostics.loadedRecords; opened.close(); const duration = performance.now() - before; check(count === 10_918 && duration <= 1_000, `cold open count=${count} duration=${duration}`); details = { loadedRecords: count, durationMs: duration, budgetMs: 1000 }; break; }
      case "PF-005": { const before = performance.now(); let pages = 0; for (let index = 0; index < 1_000; index += 1) { const page = input.catalog.queryRecords({ moduleId: "M5.SYNTH", outputSlot: "report_status", limit: 5, cursor: 0 }); check(page.records.every((record) => record.source.nativePayload.output_slot === "report_status"), "output-slot query leaked"); pages += 1; } const duration = performance.now() - before; check(duration <= 1_000, `queries took ${duration}ms`); const first = input.catalog.queryRecords({ moduleId: "M5.SYNTH", limit: 2 }); check(first.records.length === 2 && first.nextCursor === 2, "pagination cursor missing"); details = { queries: pages, durationMs: duration, budgetMs: 1000 }; break; }
      case "PF-006": { const safetyText = `${"现实描述。".repeat(20_000)}关键安全事实：明确撤回同意。`; const result = analyzeM5({ mode: "specific_partner_with_reality_data", m4: analyzeM4({ m3: unavailableM3Projection() }), gateAssessments: [{ id: "RG01", status: "fail", evidenceIds: ["long-safety"], note: safetyText }] }); check(result.safetyStatus === "safety_stop" && result.realityGates[0]?.note?.endsWith("关键安全事实：明确撤回同意。"), "long safety fact was truncated or skipped"); details = { characters: safetyText.length }; break; }
      case "PF-007": { const result = analyzeM0({ analysisMode: "test", subject: subject("UNKNOWN", true), requestedSections: ["m0"] }, input.catalog); check(result.ok && result.response.m0.status === "limited" && Object.keys(result.response.m0.fields).length === 45, "unknown-heavy input crashed or defaulted positive"); details = { fields: result.ok ? Object.keys(result.response.m0.fields).length : 0 }; break; }
      case "PF-008": { const response = success(analyzeProfile(command({ relationshipMode: "specific_partner_with_reality_data", gateAssessments: gates({ RG03: "fail" }), observations: [{ id: "dup", chainId: "M4-C01", source: "self", context: "pressure", direction: "supports" }, { id: "dup", chainId: "M4-C01", source: "self", context: "pressure", direction: "supports" }] }), input.catalog)); check(Array.isArray(response.report.logs.dedup) && response.report.logs.conflicts.length > 0 && Array.isArray(response.report.logs.discardedCandidates), "audit logs incomplete"); details = { dedup: response.report.logs.dedup.length, conflicts: response.report.logs.conflicts.length, discarded: response.report.logs.discardedCandidates.length }; break; }
      case "PF-009": { const first = success(analyzeProfile(command(), input.catalog)); const second = success(analyzeProfile(command(), input.catalog)); check(first.rulesetDigest === second.rulesetDigest && JSON.stringify(first.versionManifest) === JSON.stringify(second.versionManifest) && stable(first) === stable(second), "version manifest cannot reproduce report"); details = { rulesetDigest: first.rulesetDigest }; break; }
      case "PF-010": { const response = success(analyzeProfile(command(), input.catalog)); const before = performance.now(); for (let index = 0; index < 1_000; index += 1) check(validateRelationshipResponse(response).length === 0, "schema validation failed"); const duration = performance.now() - before; check(duration <= 3_000, `schema validation took ${duration}ms`); details = { validations: 1000, durationMs: duration, budgetMs: 3000 }; break; }
      case "PF-011": { const imported = await importCatalog({ repositoryRoot: input.repositoryRoot }); const ids = imported.runtimeRecords.map((record) => record.id); check(ids.length === 10_918 && new Set(ids).size === ids.length, "runtime CSV import count or uniqueness failed"); details = { runtimeRecords: ids.length }; break; }
      case "PF-012": { const [first, second] = await Promise.all([importCatalog({ repositoryRoot: input.repositoryRoot }), importCatalog({ repositoryRoot: input.repositoryRoot })]); check(first.runtimeRecords.length === second.runtimeRecords.length && first.runtimeRecords.every((record, index) => record.id === second.runtimeRecords[index]?.id), "repeated import produced duplicates or reordered IDs"); details = { recordsPerImport: first.runtimeRecords.length }; break; }
      case "PF-013": { const assessments = gates({ RG01: "fail" }).map((gate) => gate.id === "RG02" ? { ...gate, evidenceIds: [...gate.evidenceIds, ...Array.from({ length: 500 }, (_, index) => `positive-${index}`)] } : gate); const result = analyzeM5({ mode: "specific_partner_with_reality_data", m4: analyzeM4({ m3: unavailableM3Projection() }), gateAssessments: assessments }); check(result.reportStatus === "stop" && result.fit.grade === "FG0" && result.fit.ordinaryFindings.length === 0, "positive volume bypassed safety stop"); details = { positiveEvents: 500 }; break; }
      case "PF-014": { const response = success(analyzeProfile(command({ unavailableModules: ["M3"] }), input.catalog)); check(response.relationship.status === "dependency_pending" && response.relationship.dependencyFlags.includes("M3_MODULE_UNAVAILABLE") && response.relationship.m4 && response.relationship.m5, "M3 failure did not degrade while preserving other modules"); details = { dependency: "M3_MODULE_UNAVAILABLE" }; break; }
      case "PF-015": { const page = input.catalog.queryRecords({ moduleId: "M5.SYNTH", limit: 100 }); const match = page.records.find((record) => JSON.stringify(record.source.nativePayload).includes("关系适配总合成")); check(Boolean(match) && input.catalog.getRecord(match!.id)?.id === match!.id, "Chinese/full-width content was corrupted or unsearchable"); details = { matchedId: match?.id }; break; }
      default: throw new Error(`unmapped performance test ${testId}`);
    }
    return record(testId, true, JSON.stringify(details), startedAt);
  } catch (error) { return record(testId, false, error instanceof Error ? error.message : String(error), startedAt); }
}

function command(overrides: Partial<AnalyzeProfileCommand> = {}): AnalyzeProfileCommand { return { analysisMode: "test", subject: subject("PERF"), requestedSections: ["m0", "m1", "m2", "m3", "m4", "m5"], roleBasis: "female_traditional", relationshipMode: "single_chart_relationship_profile", ...overrides }; }
function subject(subjectId: string, unknown = false): AnalyzeProfileCommand["subject"] { return { inputMode: "four_pillars_provided", subjectId, fourPillars: { year: { stem: "庚", branch: "申" }, month: { stem: "癸", branch: "丑" }, day: { stem: "甲", branch: "寅" }, hour: unknown ? null : { stem: "丙", branch: "午" } }, birthTimeStatus: unknown ? "unknown" : "exact", timezone: "Asia/Shanghai", dataQuality: unknown ? "unknown" : "high", syntheticFixture: true }; }
function gates(overrides: Partial<Record<RealityGateAssessment["id"], RealityGateAssessment["status"]>> = {}): RealityGateAssessment[] { return (["RG01", "RG02", "RG03", "RG04", "RG05", "RG06", "RG07", "RG08"] as const).map((id) => ({ id, status: overrides[id] ?? "pass", evidenceIds: [`perf-${id}`] })); }
function success(result: ReturnType<typeof analyzeProfile>) { if (!result.ok) throw new Error(result.issues.map((issue) => issue.code).join(",")); return result.response; }
function stable(value: unknown): string { return JSON.stringify(value, (key, item) => ["requestId", "generatedAt", "analysisRunId", "decisionId"].includes(key) ? undefined : item); }
function check(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function record(testId: string, passed: boolean, actualSummary: string, startedAt: number): MatrixAssertionExecution { return Object.freeze({ testId, passed, actualSummary, durationMs: performance.now() - startedAt }); }
